// @stylescape-storybook theme.stories v1 — generated by stylescape-storybook/apply.mjs.
// =============================================================================
// src/stories/theme.stories.ts — Foundations/Theme
// =============================================================================
//
// The same file ships in every stylescape-* theme, unedited. It knows nothing
// about the brand: it reads the stylesheets the preview loaded, collects the
// custom properties declared on `:root` / `html` / `[data-theme]`, and shows
//
//   - Palette     every token whose value is a colour, grouped by prefix
//   - Typography  the font families, the font-size scale, h1–h6, body copy
//   - Elements    links, inline/block code, kbd and the button classes found
//
// Values are read from the live computed style, so switching the toolbar
// theme (light / dark / …) updates the labels as well as the swatches.
// =============================================================================

import type { Meta, StoryObj } from "@storybook/web-components-vite";
import { html, type TemplateResult } from "lit";

// -----------------------------------------------------------------------------
// Reading the theme from its stylesheets
// -----------------------------------------------------------------------------

/** Selectors that declare theme tokens: `:root`, `html`, `[data-theme…]`. */
const TOKEN_SELECTOR = /(^|[\s,(>])(:root|html)(?![\w-])|\[data-theme/;

/** Button-ish class names: `button`, `btn`, `ss-c-button`, `lc-btn`, … */
const BUTTON_BASE = /^(?:[a-z0-9]+-)?(?:c-)?(?:button|btn)$/;
const BUTTON_VARIANTS = [
    "primary",
    "secondary",
    "tertiary",
    "accent",
    "outline",
    "ghost",
    "subtle",
    "link",
    "danger",
];

interface ThemeScan {
    /** Custom properties declared on root-ish selectors, in source order. */
    tokens: string[];
    /** The subset declared per theme: `[data-theme…]` or prefers-color-scheme. */
    themed: Set<string>;
    /** Every class name that appears in a selector. */
    classes: Set<string>;
}

function walk(
    rules: CSSRuleList,
    scan: ThemeScan,
    seen: Set<string>,
    inScheme = false,
): void {
    for (const rule of Array.from(rules)) {
        if (rule instanceof CSSStyleRule) {
            const selector = rule.selectorText;
            if (TOKEN_SELECTOR.test(selector)) {
                const themed = inScheme || selector.includes("[data-theme");
                for (let i = 0; i < rule.style.length; i++) {
                    const prop = rule.style[i];
                    if (!prop.startsWith("--")) continue;
                    if (!seen.has(prop)) {
                        seen.add(prop);
                        scan.tokens.push(prop);
                    }
                    if (themed) scan.themed.add(prop);
                }
            }
            for (const m of selector.matchAll(/\.([a-zA-Z0-9_-]+)/g)) {
                scan.classes.add(m[1]);
            }
        }
        // @layer / @media / @supports / nested rules.
        const nested = (rule as CSSGroupingRule).cssRules;
        if (nested && nested.length) {
            const scheme =
                rule instanceof CSSMediaRule &&
                rule.conditionText.includes("prefers-color-scheme");
            walk(nested, scan, seen, inScheme || scheme);
        }
    }
}

function scanStylesheets(): ThemeScan {
    const scan: ThemeScan = {
        tokens: [],
        themed: new Set(),
        classes: new Set(),
    };
    const seen = new Set<string>();
    for (const sheet of Array.from(document.styleSheets)) {
        let rules: CSSRuleList;
        try {
            rules = sheet.cssRules;
        } catch {
            continue; // cross-origin sheet (e.g. a web font CDN)
        }
        walk(rules, scan, seen);
    }
    return scan;
}

function readToken(name: string): string {
    return getComputedStyle(document.documentElement)
        .getPropertyValue(name)
        .trim();
}

const NOT_A_COLOUR = new Set([
    "",
    "inherit",
    "initial",
    "unset",
    "revert",
    "currentcolor",
    "none",
]);

function isColour(value: string): boolean {
    return (
        !NOT_A_COLOUR.has(value.toLowerCase()) && CSS.supports("color", value)
    );
}

/** `--ss-color-surface-1` → `ss-color`; `--color_accent_primary--25` → `color-accent`. */
function groupOf(name: string): string {
    return name
        .replace(/^--/, "")
        .split(/[-_]+/)
        .slice(0, 2)
        .join("-")
        .replace(/-?\d+$/, ""); // `--N0001` … `--N3609` → one `N` group
}

/** Font-size in px of a token, measured by the browser (handles clamp/rem). */
function measureFontSize(name: string, probe: HTMLElement): number {
    probe.style.fontSize = `var(${name})`;
    return parseFloat(getComputedStyle(probe).fontSize) || 0;
}

// -----------------------------------------------------------------------------
// Live values: re-read every label when the theme attribute changes
// -----------------------------------------------------------------------------

function refreshValues(): void {
    for (const el of Array.from(
        document.querySelectorAll<HTMLElement>("[data-ss-token-value]"),
    )) {
        el.textContent = readToken(el.dataset.ssTokenValue ?? "") || "—";
    }
    for (const el of Array.from(
        document.querySelectorAll<HTMLElement>("[data-ss-active-theme]"),
    )) {
        el.textContent =
            document.documentElement.getAttribute("data-theme") ?? "(none)";
    }
}

let observer: MutationObserver | undefined;

function scheduleRefresh(): void {
    if (!observer) {
        observer = new MutationObserver(() =>
            requestAnimationFrame(refreshValues),
        );
        observer.observe(document.documentElement, {
            attributes: true,
            attributeFilter: ["data-theme", "class", "style"],
        });
    }
    // After lit has committed the template, and once more after any
    // decorator that sets data-theme in an effect.
    requestAnimationFrame(() => {
        refreshValues();
        requestAnimationFrame(refreshValues);
    });
}

// -----------------------------------------------------------------------------
// Layout (inline styles that only lean on the theme's own tokens + fallbacks)
// -----------------------------------------------------------------------------

const MONO =
    "var(--ss-font-family-mono, ui-monospace, SFMono-Regular, Menlo, monospace)";

const S = {
    section: "margin: 0 0 3rem;",
    h: "margin: 0 0 1rem;",
    meta: `font-family: ${MONO}; font-size: 0.75rem; opacity: 0.8; margin: 0 0 1.5rem;`,
    groupTitle: `font-family: ${MONO}; font-size: 0.8125rem; font-weight: 600; margin: 1.5rem 0 0.75rem;`,
    grid: "display: grid; grid-template-columns: repeat(auto-fill, minmax(10.5rem, 1fr)); gap: 0.75rem;",
    swatch: "height: 3rem; border-radius: 0.375rem; box-shadow: inset 0 0 0 1px rgb(128 128 128 / 0.35);",
    label: `font-family: ${MONO}; font-size: 0.6875rem; line-height: 1.35; margin-top: 0.375rem; word-break: break-all;`,
    row: "display: flex; flex-wrap: wrap; align-items: center; gap: 0.75rem; margin: 0 0 1rem;",
    scaleRow:
        "display: grid; grid-template-columns: 14rem 1fr; gap: 1rem; align-items: baseline; margin: 0 0 0.5rem;",
} as const;

function tokenValue(name: string): TemplateResult {
    return html`<span data-ss-token-value=${name}></span>`;
}

function themeMeta(scan: ThemeScan): TemplateResult {
    return html`<p style=${S.meta}>
        data-theme = <span data-ss-active-theme></span> · ${scan.tokens.length}
        custom properties on :root / [data-theme]
    </p>`;
}

// -----------------------------------------------------------------------------
// Sections
// -----------------------------------------------------------------------------

function groupColours(names: string[]): [string, string[]][] {
    const groups = new Map<string, string[]>();
    for (const name of names) {
        const key = groupOf(name);
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key)!.push(name);
    }
    // The `--ss-*` surface every theme overrides first, then the rest.
    return [...groups.entries()].sort(
        ([a], [b]) =>
            Number(b.startsWith("ss-")) - Number(a.startsWith("ss-")) ||
            a.localeCompare(b),
    );
}

function swatches(names: string[]): TemplateResult {
    return html`<div style=${S.grid}>
        ${names.map(
            (name) =>
                html`<figure style="margin: 0;">
                    <div style="${S.swatch} background: var(${name});"></div>
                    <figcaption style=${S.label}>
                        <strong>${name}</strong><br />
                        ${tokenValue(name)}
                    </figcaption>
                </figure>`,
        )}
    </div>`;
}

function palette(scan: ThemeScan): TemplateResult {
    const colours = scan.tokens.filter((n) => isColour(readToken(n)));
    // The theme's palette is what it declares per theme ([data-theme] /
    // prefers-color-scheme): those are shown open. Everything else (core
    // defaults, primitive scales, and core's snake_case `--color_*` lexicon,
    // which has dark values of its own) is listed below, folded per group.
    const themed = colours.filter(
        (n) => scan.themed.has(n) && !n.includes("_"),
    );
    const primary = themed.length ? themed : colours;
    const rest = themed.length
        ? colours.filter((n) => !themed.includes(n))
        : [];

    return html`<section style=${S.section}>
        <h2 style=${S.h}>Palette</h2>
        ${
            primary.length
                ? groupColours(primary).map(
                      ([key, names]) => html`
                          <h3 style=${S.groupTitle}>
                              --${key}-* (${names.length})
                          </h3>
                          ${swatches(names)}
                      `,
                  )
                : html`<p>No colour custom properties found on :root.</p>`
        }
        ${
            rest.length
                ? html`<h3 style=${S.groupTitle}>
                          Other colour tokens (${rest.length})
                      </h3>
                      ${groupColours(rest).map(
                          ([key, names]) =>
                              html`<details style="margin: 0 0 0.5rem;">
                                  <summary style=${S.label}>
                                      --${key}-* (${names.length})
                                  </summary>
                                  ${swatches(names)}
                              </details>`,
                      )}`
                : ""
        }
    </section>`;
}

function typography(scan: ThemeScan): TemplateResult {
    const families = scan.tokens.filter((n) =>
        /font-(family|stack)|font-(sans|serif|mono|display|heading|body)$/.test(
            n,
        ),
    );

    // Measure the size scale off-screen, then sort by rendered size.
    const probe = document.createElement("div");
    probe.style.cssText = "position: absolute; visibility: hidden;";
    document.body.append(probe);
    let sizeTokens = scan.tokens.filter((n) =>
        /font-size|text-size|type-size|(^|-)fs-/.test(n),
    );
    // Prefer the semantic scale over the primitive steps it aliases.
    const semantic = sizeTokens.filter((n) => !n.includes("primitive"));
    if (semantic.length) sizeTokens = semantic;
    const sizes = sizeTokens
        .map((name) => ({ name, px: measureFontSize(name, probe) }))
        .filter((s) => s.px > 0)
        .sort((a, b) => a.px - b.px);
    probe.remove();

    return html`<section style=${S.section}>
        <h2 style=${S.h}>Typography</h2>

        <h3 style=${S.groupTitle}>Headings</h3>
        <h1>Heading 1 — The quick brown fox</h1>
        <h2>Heading 2 — The quick brown fox</h2>
        <h3>Heading 3 — The quick brown fox</h3>
        <h4>Heading 4 — The quick brown fox</h4>
        <h5>Heading 5 — The quick brown fox</h5>
        <h6>Heading 6 — The quick brown fox</h6>

        <h3 style=${S.groupTitle}>Body</h3>
        <p>
            Body text sets the reading rhythm of the theme. It carries
            <strong>strong emphasis</strong>, <em>emphasis</em>,
            <a href="#body-link">an inline link</a>,
            <code>inline code</code> and <small>small print</small> in the same
            line, so their weights and colours can be judged against each
            other.
        </p>
        <p>
            A second paragraph shows the space between paragraphs and how a
            longer measure wraps. Pack my box with five dozen liquor jugs —
            0123456789.
        </p>
        <blockquote>
            A blockquote, for pulled quotations and callouts.
        </blockquote>
        <ul>
            <li>Unordered list item</li>
            <li>Another item</li>
        </ul>
        <ol>
            <li>Ordered list item</li>
            <li>Another item</li>
        </ol>

        ${
            families.length
                ? html`<h3 style=${S.groupTitle}>Font families</h3>
                      ${families.map(
                          (name) =>
                              html`<div style=${S.scaleRow}>
                                  <span style=${S.label}>${name}</span>
                                  <span
                                      style="font-family: var(${name}); font-size: 1.25rem;"
                                  >
                                      Sphinx of black quartz, judge my vow 0123
                                  </span>
                              </div>`,
                      )}`
                : ""
        }
        ${
            sizes.length
                ? html`<h3 style=${S.groupTitle}>Size scale</h3>
                      ${sizes.map(
                          ({ name, px }) =>
                              html`<div style=${S.scaleRow}>
                                  <span style=${S.label}
                                      >${name}<br />${Math.round(px * 10) / 10}px
                                      · ${tokenValue(name)}</span
                                  >
                                  <span
                                      style="font-size: var(${name}); line-height: 1.2; overflow-wrap: anywhere;"
                                      >The quick brown fox</span
                                  >
                              </div>`,
                      )}`
                : ""
        }
    </section>`;
}

function rank(cls: string): number {
    if (cls.startsWith("ss-")) return 2;
    return cls.includes("-") ? 0 : 1;
}

function buttonClasses(
    scan: ThemeScan,
): { base: string; variants: string[] }[] {
    const bases = [...scan.classes]
        .filter((c) => BUTTON_BASE.test(c))
        // Theme-namespaced classes (`lc-btn`) first, then bare ones
        // (`button`), then core's `ss-*`.
        .sort((a, b) => rank(a) - rank(b) || a.localeCompare(b))
        .slice(0, 4);
    return bases.map((base) => ({
        base,
        variants: BUTTON_VARIANTS.flatMap((v) =>
            [`${base}--${v}`, `${base}-${v}`].filter((c) =>
                scan.classes.has(c),
            ),
        ).slice(0, 6),
    }));
}

function elements(scan: ThemeScan): TemplateResult {
    return html`<section style=${S.section}>
        <h2 style=${S.h}>Elements</h2>

        <h3 style=${S.groupTitle}>Links</h3>
        <p style=${S.row}>
            <a href="#link">Default link</a>
            <a href="#visited">Another link</a>
            <a href="#strong"><strong>Strong link</strong></a>
        </p>

        <h3 style=${S.groupTitle}>Code</h3>
        <p>
            Inline <code>const theme = "light"</code>, keyboard
            <kbd>Ctrl</kbd> + <kbd>K</kbd>, sample <samp>output</samp>.
        </p>
        <pre><code>@use "pkg:stylescape/scss" as core;

:root {
    --ss-color-accent: #3b5bdb;
}</code></pre>

        <h3 style=${S.groupTitle}>Buttons</h3>
        <div style=${S.row}>
            <button type="button">Native button</button>
            <button type="button" disabled>Disabled</button>
        </div>
        ${buttonClasses(scan).map(
            ({ base, variants }) =>
                html`<div style=${S.row}>
                    <button type="button" class=${base}>.${base}</button>
                    ${variants.map(
                        (v) =>
                            html`<button type="button" class="${base} ${v}">
                                .${v}
                            </button>`,
                    )}
                    <button type="button" class=${base} disabled>
                        Disabled
                    </button>
                </div>`,
        )}
    </section>`;
}

// -----------------------------------------------------------------------------
// Stories
// -----------------------------------------------------------------------------

function view(...parts: ((scan: ThemeScan) => TemplateResult)[]) {
    return (): TemplateResult => {
        const scan = scanStylesheets();
        scheduleRefresh();
        return html`<div
            style="color: var(--ss-color-text, inherit); background: var(--ss-color-background, transparent); font-family: var(--ss-font-family-base, inherit);"
        >
            ${themeMeta(scan)} ${parts.map((part) => part(scan))}
        </div>`;
    };
}

const meta: Meta = {
    title: "Foundations/Theme",
    parameters: { layout: "padded" },
};

export default meta;

type Story = StoryObj;

export const Overview: Story = { render: view(palette, typography, elements) };
export const Palette: Story = { render: view(palette) };
export const Typography: Story = { render: view(typography) };
export const Elements: Story = { render: view(elements) };
