// @stylescape-storybook main v1 — generated by stylescape-storybook/apply.mjs.
// =============================================================================
// .storybook/main.ts — Storybook for a stylescape-* theme
// =============================================================================
//
// Aligned with core stylescape's `.storybook/main.ts` (docs, a11y and themes
// addons; Sass NodePackageImporter; telemetry off). The renderer is
// web-components + Vite so stories are lit `html` templates, as in the other
// theme Storybooks (cardean, lakeor, lectence, tbgo, texl).
//
// `viteFinal` does two things to the config Storybook merges in from the
// repo's own `vite.config.ts`:
//
//   1. Sass: register the NodePackageImporter so the theme's
//      `pkg:stylescape/scss` (core) load resolves, keeping any other Sass
//      options the repo set, and quiet core's upstream deprecations.
//   2. Build: drop the LIBRARY half of the repo's build (`build.lib` and the
//      rollup/rolldown output naming). Left in, `storybook build` turns into a
//      second `npm run build` instead of building the Storybook app.
// =============================================================================

import type { StorybookConfig } from "@storybook/web-components-vite";
import { NodePackageImporter } from "sass";

const config: StorybookConfig = {
    stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|ts)"],

    addons: [
        "@storybook/addon-docs",
        "@storybook/addon-a11y",
        "@storybook/addon-themes",
    ],

    framework: {
        name: "@storybook/web-components-vite",
        options: {},
    },

    core: {
        // Open-source design themes; opt out of usage analytics, like core.
        disableTelemetry: true,
    },

    async viteFinal(viteConfig) {
        // --- 1. Sass -----------------------------------------------------------
        viteConfig.css ??= {};
        viteConfig.css.preprocessorOptions ??= {};
        const scss = (viteConfig.css.preprocessorOptions.scss ?? {}) as Record<
            string,
            unknown
        >;
        const importers = Array.isArray(scss.importers) ? scss.importers : [];
        viteConfig.css.preprocessorOptions.scss = {
            ...scss,
            importers: importers.some((i) => i instanceof NodePackageImporter)
                ? importers
                : [...importers, new NodePackageImporter()],
            quietDeps: true,
            silenceDeprecations: [
                "import",
                "global-builtin",
                "color-functions",
                "mixed-decls",
                "legacy-js-api",
                "if-function",
                "slash-div",
                "function-units",
                "abs-percent",
                "feature-exists",
                "duplicate-var-flags",
            ],
        };

        // --- 2. Build as an app, not as the theme's library ---------------------
        if (viteConfig.build) {
            const build = viteConfig.build as Record<string, unknown>;
            delete build.lib;
            for (const key of ["rollupOptions", "rolldownOptions"]) {
                const opts = build[key] as Record<string, unknown> | undefined;
                const output = opts?.output as
                    Record<string, unknown> | undefined;
                // Storybook sets `external` and `output.strictExecutionOrder`
                // here itself; only the lib build's fixed file naming goes.
                if (output && !Array.isArray(output)) {
                    delete output.assetFileNames;
                    delete output.entryFileNames;
                    delete output.chunkFileNames;
                }
            }
            // Storybook has already written the manager into the output dir
            // when the preview builds; a repo's `emptyOutDir: true` would wipe it.
            build.emptyOutDir = false;
            // The large chunks are Storybook's own runtime, not the stories.
            build.chunkSizeWarningLimit = 1500;
        }

        return viteConfig;
    },
};

export default config;
