// @stylescape-storybook preview v1 — generated by stylescape-storybook/apply.mjs.
// =============================================================================
// .storybook/preview.ts — the theme's own entry, and its themes
// =============================================================================
//
// Loads the theme exactly as its package exports it (see `exports` in
// package.json), compiled from source by Vite (`viteFinal` in main.ts), so
// every story reflects `src/scss/**` with HMR. The toolbar theme switch stamps
// `data-theme` on <html>, the hook the theme's `[data-theme]` blocks key off.
// =============================================================================

import type { Preview } from "@storybook/web-components-vite";
import { withThemeByDataAttribute } from "@storybook/addon-themes";

// @stylescape-storybook:imports
import "../src/font/fonts.css";
import "../src/scss/index.scss";
// @stylescape-storybook:imports-end

const preview: Preview = {
    parameters: {
        // The theme paints its own background; the toolbar drives data-theme.
        backgrounds: { disable: true },
        layout: "padded",
        controls: {
            matchers: {
                color: /(background|color)$/i,
                date: /Date$/i,
            },
        },
        options: {
            storySort: {
                order: ["Introduction", "Foundations", "Components", "*"],
            },
        },
        a11y: {
            // Surface accessibility findings in the panel without failing CI.
            test: "todo",
        },
    },

    decorators: [
        withThemeByDataAttribute({
            // @stylescape-storybook:themes
            themes: { light: "light", dark: "dark", auto: "auto" },
            // @stylescape-storybook:themes-end
            defaultTheme: "light",
            attributeName: "data-theme",
        }),
    ],
};

export default preview;
